
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#antigen
source $HOME/.dotfiles/zsh/antigen/antigen.zsh
    #antigen bundles
    antigen bundle kennethreitz/autoenv
#alias
source $HOME/.dotfiles/zsh/alias
##functions
source $HOME/.dotfiles/zsh/functions
##private
source $HOME/.dotfiles/zsh/private
##completion
# -> .zshenv
source /usr/local/share/zsh/site-functions/_aws
##folder
source $HOME/.dotfiles/zsh/folders
# npm autocomplete fix
eval "$(npm completion 2>/dev/null)"
